### ISSUE TITLE
 Argument 1 passed to FFMpeg\FFProbe::__construct() must be FFProbeDriver instance, array given

### ISSUE THREAD

**Issue by rpac-tump** [xmon/SonataMediaProviderVideoBundle#7]
Firstly, thank you for your bundle.
When i try to upload a video (.mp4) from my sonata media backend, I have this error (Sf 3.1.5) :
Catchable Fatal Error: Argument 1 passed to FFMpeg\FFProbe::__construct() must be an instance of FFMpeg\Driver\FFProbeDriver, array given, called in D:\wamp\www\test-sf3\TestSonata\var\cache\dev\appDevDebugProjectContainer.php

Could you please help me to solve this issue, thank you for your help as i'm stuck !
Here's a a capture of the stack trace : 
![ssss1](https://cloud.githubusercontent.com/assets/25033486/21808682/a139b69c-d744-11e6-96a9-48c8777aa71f.jpg)

**Comment by rpac-tump** [comment]
I have posted a solution here : http://stackoverflow.com/a/41647552/7403405

**Comment by xmon** [comment]
Thanks @RichardMalaure 

I study your problem and solution, I'll try to implement to a new version for Symfony3.
